// Employees
const SET_EMPLOYEES = "FETCH_EMPLOYEES";
const SET_FILTERED_EMPLOYEES = "SET_FILTERED_EMPLOYEES";
const SET_FILTERS = "SET_FILTERS";
const RESET_FILTERS = "RESET_FILTERS";
const FILTER_SORT_EMPLOYEES = "FILTER_SORT_EMPLOYEES";
const SET_SORT_BY = "SET_SORT_BY";
const SET_SORT_ORDER = "SET_SORT_ORDER";

// Skills
const SET_SKILLS = "SET_SKILLS";

// Department
const SET_DEPARTMENTS = "SET_DEPARTMENTS";

// Roles
const SET_ROLES = "SET_ROLES";

export default {
  SET_EMPLOYEES,
  SET_FILTERED_EMPLOYEES,
  FILTER_SORT_EMPLOYEES,
  SET_FILTERS,
  RESET_FILTERS,
  SET_SORT_BY,
  SET_SORT_ORDER,
  SET_SKILLS,
  SET_DEPARTMENTS,
  SET_ROLES,
};
