// Employees
const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
const SET_FILTERED_EMPLOYEES = "SET_FILTERED_EMPLOYEES";
const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";
const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE";
const FILTER_BY_DEPARTMENT = "FILTER_BY_DEPARTMENT";
const FILTER_BY_ROLE = "FILTER_BY_ROLE";
const FILTER_BY_SKILLS = "FILTER_BY_SKILLS";

// Skills
const FETCH_SKILLS = "FETCH_SKILLS";

export default {
  FETCH_EMPLOYEES,
  SET_FILTERED_EMPLOYEES,
  FILTER_EMPLOYEES,
  SEARCH_EMPLOYEE,
  FILTER_BY_DEPARTMENT,
  FILTER_BY_ROLE,
  FILTER_BY_SKILLS,
  FETCH_SKILLS,
};
